osx_image: xcode9
language: objective-c

cache:
  - bundler
  - cocoapods

env:
    global:
        - LC_CTYPE=en_US.UTF-8
        - LANG=en_US.UTF-8

script:
  - set -o pipefail
  - xcodebuild test -workspace BeKindRewind.xcworkspace -scheme SwiftTests-iOS -destination 'platform=iOS Simulator,name=iPhone 7,OS=10.3.1' -destination 'platform=iOS Simulator,name=iPhone 7,OS=11.0' | xcpretty
  - pod lib lint

after_failure:
 - cat -n ~/Library/Logs/scan/*
 - cat -n $TMPDIR/com.apple.dt.XCTest-status/Session*.log
 - cat -n ~/Library/Logs/DiagnosticReports/xctest*.crash
