language: objective-c
sudo: false
osx_image: xcode7.3
cache: cocoapods
env:
    global:
        - LC_CTYPE=en_US.UTF-8
        - LANG=en_US.UTF-8
        - FASTLANE_LANE=ci_commit
matrix:
  include:
    # iOS 8.1
    - env: FASTLANE_ENV=ios81_iPad2
    # iOS 8.2
    - env: FASTLANE_ENV=ios82_iPhone5
    # iOS 8.3
    - env: FASTLANE_ENV=ios83_iPhone5S
    # iOS 8.4
    - env: FASTLANE_ENV=ios84_iPhone4S
    # iOS 9.0
    - env: FASTLANE_ENV=ios90_iPadRetina
    # iOS 9.1
    - env: FASTLANE_ENV=ios91_iPhone6S
    # iOS 9.2
    - env: FASTLANE_ENV=ios92_iPadPro
    # iOS 9.3
    - env: FASTLANE_ENV=ios93_iPhone6Plus
    # OSX
    - env: FASTLANE_ENV=osx
    # tvOS 9.0
    - env: FASTLANE_ENV=tvos90_AppleTV1080p
    # tvOS 9.1
    - env: FASTLANE_ENV=tvos91_AppleTV1080p
    # tvOS 9.2
    - env: FASTLANE_ENV=tvos92_AppleTV1080p
before_install:
  - gem install fastlane --no-rdoc --no-ri --no-document --quiet
  - gem install cocoapods --no-rdoc --no-ri --no-document --quiet
  - gem install xcpretty --no-rdoc --no-ri --no-document --quiet
script:
  - set -o pipefail
  - export COCOAPODS_DISABLE_DETERMINISTIC_UUIDS=YES # remove this when Cocoapods upgrades to 1.0.0
  - fastlane $FASTLANE_LANE configuration:Debug --env $FASTLANE_ENV
  - fastlane $FASTLANE_LANE configuration:Release --env $FASTLANE_ENV
after_success:
  # - if [ "$FASTLANE_LANE" == "code_coverage" ]; then
  #    bash <(curl -s https://codecov.io/bash);
  #   fi
after_failure:
 - cat -n fastlane/report.xml
 - cat -n ~/Library/Logs/scan/*
 - cat -n $TMPDIR/com.apple.dt.XCTest-status/Session*.log
 - cat -n ~/Library/Logs/DiagnosticReports/xctest*.crash
